django:
  debug: false
  secret_key: v8+4d(w%u@lzxcwl-w#i1h07=qdyecs@+%41bkejx^t5g_=tib
  allowed_hosts:
    - promort.local
  static_root: ./static/
  session_cookie: promort_sessionid

database:
  engine: postgresql
  name: promort
  user: promort
  password: promort
  host: promort-db
  port: 5432

email:
  use_tls: true
  host:
  port:
  user:
  password:

report:
  subject_prefix: "[ProMort]"
  recipients: []

promort_groups:
  rois_manager:
    name: ROIS_MANAGERS
  clinical_manager:
    name: CLINICAL_MANAGERS 
  gold_standard:
    name: GOLD_STANDARD
  odin_members:
    name: ODIN_USERS

ome_seadragon:
  base_url: http://ome-seadragon.local/ome_seadragon/
  static_files_url: http://ome-seadragon.local/static/
